[package]
name = "neo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.8"
walkdir = "2.5.0"
unicode-segmentation = "1.1.0"

[[bin]]
name = "calculate_zos"
path = "src/calculate_zos.rs"
